### PR TITLE
Action logs enhancement

### PR DESCRIPTION
**Pull request by FabrizioSandri**
The purpose of this pull request is to improve the action logs when run outside of a pull request. The logs have been reorganized and grouped so that the user may collapse a group and see only the relevant details.

### CODE REVIEW

**Comment by FabrizioSandri** [comment]
With the last commit I added a branding icon for the action; this will be used on the GitHub marketplace.

**Comment by tdhock** [comment]
can you post a link to the new output?

**Comment by FabrizioSandri** [comment]
[Here's a link](https://github.com/FabrizioSandri/RcppDeepState-action/runs/8201000673?check_suite_focus=true) to the latest updated output. As you can see, various parts of the logs(dependencies setup, package installation and analysis) have been grouped together to allow the user to focus on the results. Each group may be extended by clicking on it. 

Schermata del 2022-09-06 18-38-09

**Comment by tdhock** [comment]
great!

**Pull request merged**
