### PR TITLE
Action's comments

### PR DESCRIPTION
**Pull request by FabrizioSandri**
This pull request aims to enhance the action's commenting system.

### CODE REVIEW

**Comment by FabrizioSandri** [comment]
In the last few commits I've made improvements to the case where RcppDeepState finds no errors. I've temporarily turned off the workflow that tests testSAN in favor of checking TestPackage, a package that is known to be error-free. 

As can be seen from the most recent gtihub-actions comment, a table showing the summary of each examined function with the number of tests run has been included with the message "No error has been reported by RcppDeepState".

**Comment by FabrizioSandri** [comment]
@tdhock In this pull request I also managed to add a third option for the comment argument. There are three choices:
* `true`: if set to `true` the GitHub action adds a comment to the pull request whether or not RcppDeepState finds any errors;
* `failure`: adds a comment to the pull request only when RcppDeepState finds at least one error;
* `false`: the action simply runs in background without actually bothering the user with comments.

This has been tested in the last action execution triggered by the commit f7c351c. The action has been run on the bug-free package with the comment parameter set to `failure`. We can see from the analysis that the package contains no errors, hence no comments have been added.

**Comment by FabrizioSandri** [comment]
To recap the changes made in this pull request, I implemented the following features:
* additional information about which functions were tested, and with how many random inputs when no error is found. 
Test: [this comment](https://github.com/FabrizioSandri/RcppDeepState-action/pull/6#issuecomment-1196570329);
* third option for the `comment` parameter; the `failure` value. This tells the action to comment only when there is a failure.
Test: workflow triggered in the commit f7c351c.

**Comment by tdhock** [comment]
that "Analyzed functions summary" looks good!

**Comment by FabrizioSandri** [comment]
@tdhock I changed the action such that it adds the comment once in a pull request and updates it in subsequent runs.

Running twice the action on the testSAN package allowed me to test this functionality. The [final comment ](https://github.com/FabrizioSandri/RcppDeepState-action/pull/6#issuecomment-1197975256) illustrates the result: the comment has been created on the first run of job and then updated on the second run.

* [Link to the first job run](https://github.com/FabrizioSandri/RcppDeepState-action/actions/runs/2753035190/attempts/1) 
* [Link to the second job run](https://github.com/FabrizioSandri/RcppDeepState-action/actions/runs/2753035190/attempts/2)

**Comment by FabrizioSandri** [comment]
I noticed that although the `comment` option in https://github.com/tdhock/binsegRcpp/pull/13 was set to `true`, no comment had been included.
I discovered that the issue was caused by the `fail ci if error` option being set to `true`, which prevented the execution of the subsequent steps. To solve this, I modified the conditions that are applied when the step that adds a comment runs.

**Comment by FabrizioSandri** [comment]
> that "Analyzed functions summary" looks good!

Does it make sense to include the "Analyzed functions summary" even if RcppDeepState discovers errors? For now that summary is printed only in the case RcppDeepState finds at least one error.

**Pull request merged**
