### PR TITLE
First prototype

### PR DESCRIPTION
**Pull request by FabrizioSandri**
## First prototype
In this pull request I will create a first prototype of the RcppDeepState GitHub Action.

## Considerations
The blog article titled "[RcppDeepState's GitHub Action considerations](https://fabriziosandri.github.io/gsoc-2022-blog/github%20action/2022/06/28/github-actions.html)" contains various aspects that I had to take into account when writing this GitHub Action. I made the decision to create a Docker-based GitHub Action. The more flexible aspect of a docker-based action played a role in this choice; perhaps in the future, this Action could be rewritten as a composite action rather than a docker one.

### CODE REVIEW

**Comment by FabrizioSandri** [comment]
@tdhock with the end of this week I've created a first working prototype of the RcppDeepState Action. However, this prototype requires several adjustments, including to inputs and outputs.

To test this action I made a simple workflow that checks-out the [RcppDeepState](https://github.com/FabrizioSandri/RcppDeepState) repository containing the testSAN package and then runs RcppDeepState on it. 

The [execution of the workflow](https://github.com/FabrizioSandri/RcppDeepState-action/runs/7149372027), triggered by the commit 32d35d3, shows the results of the RcppDeepState's analysis over the testSAN package. The analysis's resulting logtable is printed at the end of the step named `Analyze the package with RcppDeepState`.

**Comment by tdhock** [comment]
Hi I see the RcppDeepState output on the github action run. This is great progress! What's next?

**Comment by FabrizioSandri** [comment]
These are the tasks I have planned for as my next steps for the RcppDeepState-action:
* implement exit codes for the Action so that the workflow will fail if an error is discovered;
* add the following parameters as inputs for the action:
    * `seed`: input parameter that will be used as an input seed for deterministic fuzz testing;
    * `time_limit`: used to control the time which the fuzzing phase will be run;
    * `max_inputs`: used to provide a maximum number of inputs to analyze;
* improve the output of RcppDeepState, so that the developer that runs this action will be able to quickly find and understand the motivation behind bugs;

In the future, I'll also think about if I can express this Action as a composite action. This is merely an idea at this time, though.
If I intend to make this change, I'll probably add a step `actions/upload-artifact` to share the analysis findings with other jobs. In this way developers that use this Action will be able to download the artifact files to see the analysis results. 
<hr />
On the RcppDeepState side I will finish making some changes to the logging system, as outlined in the pull request [Logging improvements #9](https://github.com/FabrizioSandri/RcppDeepState/pull/9). 
Additionally I plan to create a new RcppDeepState function that sets up a workflow inside of a repository. In this way it will be easy for developers to initialize RcppDeepState-action.

**Comment by tdhock** [comment]
sounds great full speed ahead, tell me if you need to discuss via google meet some time.

**Comment by FabrizioSandri** [comment]
Yes, before the end of this week I will send you an email to plan the meeting.

**Pull request merged**
